-- Insert sample business listings
INSERT INTO public.business_listings (
  business_name, description, category, city, state, email, phone, website,
  instagram, facebook, listing_type, is_active, payment_status, amount_paid,
  cover_image_url
) VALUES 
(
  'Bloom Beauty Bar',
  'Luxury beauty services for the modern woman entrepreneur. Specializing in hair styling, makeup, and wellness treatments.',
  'Beauty & Wellness',
  'Atlanta',
  'GA',
  'hello@bloombeautybar.com',
  '404-555-0123',
  'https://bloombeautybar.com',
  '@bloombeautybar',
  'facebook.com/bloombeautybar',
  'featured',
  true,
  'completed',
  49,
  '/lovable-uploads/316cf67d-f73c-4fc8-b3b0-c054aa99fde2.png'
),
(
  'Tech Savvy Solutions',
  'IT consulting and digital transformation for small businesses. We help you leverage technology to grow.',
  'Technology',
  'Los Angeles',
  'CA',
  'info@techsavvy.io',
  '213-555-0456',
  'https://techsavvy.io',
  '@techsavvysolutions',
  'facebook.com/techsavvy',
  'featured',
  true,
  'completed',
  49,
  '/lovable-uploads/6326d9ea-3f1e-49ce-a6de-ab9b6907e4b6.png'
),
(
  'Soulful Eats Catering',
  'Authentic soul food catering for events of all sizes. From intimate gatherings to corporate events.',
  'Food & Beverage',
  'Chicago',
  'IL',
  'catering@soulfuleats.com',
  '312-555-0789',
  'https://soulfuleats.com',
  '@soulfuleats',
  'facebook.com/soulfuleats',
  'standard',
  true,
  'completed',
  25,
  '/lovable-uploads/49583cd3-b56e-4845-ab46-3dac09dbd1ac.png'
),
(
  'Elegance Boutique',
  'Curated fashion for the confident woman. Contemporary clothing, accessories, and styling services.',
  'Retail',
  'New York',
  'NY',
  'shop@eleganceboutique.com',
  '212-555-0321',
  'https://eleganceboutique.com',
  '@eleganceboutique',
  'facebook.com/eleganceboutique',
  'featured',
  true,
  'completed',
  49,
  '/lovable-uploads/7d82b6d9-3e36-4297-b7b6-e340cc37eeae.png'
),
(
  'Bright Minds Tutoring',
  'Professional tutoring services for K-12 students. We specialize in STEM subjects and test prep.',
  'Education',
  'Houston',
  'TX',
  'learn@brightminds.edu',
  '713-555-0654',
  'https://brightminds.edu',
  '@brightmindstutoring',
  'facebook.com/brightminds',
  'standard',
  true,
  'completed',
  25,
  '/lovable-uploads/8d850553-3b5c-492c-9401-c6aaf29d07c9.png'
),
(
  'Wellness Within Spa',
  'Holistic wellness and spa treatments. Massage therapy, facials, and body treatments.',
  'Beauty & Wellness',
  'Miami',
  'FL',
  'relax@wellnesswithin.com',
  '305-555-0987',
  'https://wellnesswithin.com',
  '@wellnesswithinspa',
  'facebook.com/wellnesswithin',
  'featured',
  true,
  'completed',
  49,
  '/lovable-uploads/a9699e21-9904-4794-9554-eaff3efc955a.png'
),
(
  'Creative Studios',
  'Graphic design, branding, and marketing services for small businesses and startups.',
  'Professional Services',
  'Seattle',
  'WA',
  'hello@creativestudios.co',
  '206-555-0246',
  'https://creativestudios.co',
  '@creativestudios',
  'facebook.com/creativestudios',
  'standard',
  true,
  'completed',
  25,
  '/lovable-uploads/ab2b2116-36e6-4d43-83e5-d3289f08bf9a.png'
),
(
  'Fresh Harvest Market',
  'Organic produce and locally sourced goods. Supporting local farmers and healthy living.',
  'Food & Beverage',
  'Portland',
  'OR',
  'shop@freshharvestmarket.com',
  '503-555-0135',
  'https://freshharvestmarket.com',
  '@freshharvestmarket',
  'facebook.com/freshharvestmarket',
  'standard',
  true,
  'completed',
  25,
  '/lovable-uploads/bb07af18-2beb-44e5-a9da-b290ab7c54de.png'
),
(
  'Kingdom Realty Group',
  'Full-service real estate agency specializing in residential and commercial properties.',
  'Real Estate',
  'Atlanta',
  'GA',
  'agents@kingdomrealty.com',
  '404-555-0852',
  'https://kingdomrealty.com',
  '@kingdomrealty',
  'facebook.com/kingdomrealty',
  'featured',
  true,
  'completed',
  49,
  '/lovable-uploads/c7ce2bf2-7c2d-4583-8804-83d2ba602e6a.png'
),
(
  'Harmony Health Clinic',
  'Comprehensive healthcare services with a focus on preventive care and wellness.',
  'Healthcare',
  'Dallas',
  'TX',
  'care@harmonyhealth.com',
  '214-555-0741',
  'https://harmonyhealth.com',
  '@harmonyhealthclinic',
  'facebook.com/harmonyhealth',
  'standard',
  true,
  'completed',
  25,
  '/lovable-uploads/d51ba94c-7ed2-47ff-a662-f9479d1b7c29.png'
),
(
  'Crown Consulting',
  'Business strategy and management consulting for entrepreneurs and small business owners.',
  'Professional Services',
  'Washington',
  'DC',
  'consult@crownconsulting.com',
  '202-555-0963',
  'https://crownconsulting.com',
  '@crownconsulting',
  'facebook.com/crownconsulting',
  'standard',
  true,
  'completed',
  25,
  '/lovable-uploads/e8248008-7075-4ddc-84c0-cedcfbd591e3.png'
),
(
  'The Style Lounge',
  'Upscale hair salon and styling studio. Specializing in natural hair care and protective styles.',
  'Beauty & Wellness',
  'Charlotte',
  'NC',
  'book@thestylelounge.com',
  '704-555-0147',
  'https://thestylelounge.com',
  '@thestylelounge',
  'facebook.com/thestylelounge',
  'featured',
  true,
  'completed',
  49,
  '/lovable-uploads/f69cd8b7-133e-409e-8d8d-01334ca7a6fe.png'
);